import RiemannHypothesis.Certificates.Generated.NymanGramN1
import RiemannHypothesis.Certificates.Generated.NymanGramN2
import RiemannHypothesis.Certificates.Generated.NymanGramN3
import RiemannHypothesis.Certificates.Generated.NymanGramN5
import RiemannHypothesis.Certificates.Generated.NymanGramN10
import RiemannHypothesis.Certificates.Generated.NymanGramN20
import RiemannHypothesis.Certificates.Generated.NymanGramN50
